/**
 * @module Experience
 * @category Player Experience
 *
 * Player Experience - Cameras, Input, Audio, and UI
 *
 * Everything that connects the player to your game - how they see it,
 * how they control it, what they hear, and what information they receive.
 */

export type {
    AmbientAudioProps,
    AmbientAudioRef,
    AudioEmitterProps,
    AudioEmitterRef,
    AudioEnvironmentProps,
    AudioListenerProps,
    AudioProviderProps,
    AudioZoneProps,
    AudioZoneRef,
    CameraShakeProps,
    CameraShakeRef,
    CinematicCameraProps,
    CinematicCameraRef,
    CrosshairProps,
    DamageNumberProps,
    DialogBoxProps,
    DialogBoxRef,
    FollowCameraProps,
    FollowCameraRef,
    FootstepAudioProps,
    FootstepAudioRef,
    FPSCameraProps,
    FPSCameraRef,
    GroundSwitchProps,
    GroundSwitchRef,
    HealthBarProps,
    HealthBarRef,
    InventoryProps,
    InventoryRef,
    Joystick3DProps,
    Joystick3DRef,
    MinimapProps,
    NameplateProps,
    NameplateRef,
    NotificationProps,
    OrbitCameraProps,
    OrbitCameraRef,
    PositionalAudioProps,
    PositionalAudioRef,
    PressurePlateProps,
    PressurePlateRef,
    ProgressBar3DProps,
    TooltipProps,
    TriggerComposerProps,
    TriggerComposerRef,
    WallButtonProps,
    WallButtonRef,
    WeatherAudioProps,
} from '../components';

export {
    AmbientAudio,
    AudioEmitter,
    AudioEnvironment,
    AudioListener,
    AudioProvider,
    AudioZone,
    CameraShake,
    CinematicCamera,
    Crosshair,
    DamageNumber,
    DialogBox,
    FollowCamera,
    FootstepAudio,
    FPSCamera,
    GroundSwitch,
    HealthBar,
    Inventory,
    Joystick3D,
    Minimap,
    Nameplate,
    Notification,
    OrbitCamera,
    PositionalAudio,
    PressurePlate,
    ProgressBar3D,
    Tooltip,
    TriggerComposer,
    useAudioContext,
    useAudioManager,
    useCameraTransition,
    WallButton,
    WeatherAudio,
} from '../components';

export type {
    AudioBus,
    AudioConfig,
    AudioFormat,
    AudioListenerState,
    AudioMixer,
    CameraPath,
    CameraShakeConfig,
    CrosshairConfig,
    DamageNumberConfig,
    DialogChoice,
    DialogConfig,
    DialogLine,
    DistanceModel,
    EnvironmentEffectConfig,
    EnvironmentPreset,
    FOVTransitionConfig,
    InventoryConfig,
    InventorySlot,
    MinimapConfig,
    MinimapMarker,
    NameplateConfig,
    NotificationConfig,
    ProgressBarConfig,
    ScreenPosition,
    ScreenShakeIntensity,
    SoundConfig,
    SpatialConfig,
    TextDirection,
    TooltipConfig,
    UIAnchor,
} from '../core';

export {
    CameraShake as CoreCameraShake,
    createDefaultCrosshair,
    createDefaultDamageNumber,
    createDefaultDialog,
    createDefaultInventory,
    createDefaultMinimap,
    createDefaultNameplate,
    createDefaultNotification,
    createDefaultProgressBar,
    createDefaultTooltip,
    createSoundManager,
    createSpatialAudio,
    DEFAULT_SPATIAL_CONFIG,
    ENVIRONMENT_PRESETS,
    easeInCubic,
    easeInOutCubic,
    easeOutCubic,
    easeOutElastic,
    evaluateCatmullRom,
    FOVTransition,
    formatNumber,
    getAnchorOffset,
    getAudioContext,
    getDamageNumberColor,
    getNotificationColor,
    getNotificationIcon,
    getTextDirection,
    Howl,
    Howler,
    isAudioContextUnlocked,
    lerp,
    lerpVector3,
    resumeAudioContext,
    SoundManager,
    SpatialAudio,
    screenToWorld,
    setupAutoUnlock,
    slerp,
    smoothDamp,
    smoothDampVector3,
    suspendAudioContext,
    unlockAudioContext,
    worldToScreen,
    calculateFade,
    calculateHeadBob,
    calculateLookAhead,
    calculateScreenShakeIntensity,
    clampProgress,
    formatProgressText,
} from '../core';
